### ISSUE TITLE
Bad format for predefined-setting "Université Lille 2"

### ISSUE THREAD

**Issue by a-cordier** [ezpaarse-project/ezpaarse-resources#1]
Hi,
predefined-settings.json currently contains the following entry for "Log-Format-ezproxy":

"%h %{ezproxy-groups}i %l %u %t \"%r\" %s %b"

we found here that due to our ezproxy configuration the entry should look like so

"%h %{ezproxy-groups}<[a-zA-Z0-9+]+> %l %u %t \"%r\" %s %b"

We tried to update locally predefined-settings.json but as a result we just get a broken list-box in the UI

Can you help in setting this field properly ?

Thank you

**Comment by tporquet** [comment]
Hello Antoine,

I just pushed the modified predefined-setting for Lille 2
You only need to go to the admin tab, and on the "Resources" sub-tab and click on the "update" button. Don't forget to refresh the page (F5) afterwards in order to see the change.
The new predefined setting seems to be working on a log extract of your, dating april this year.

Best,
Thomas

**Comment by a-cordier** [comment]
It works, thank you Thomas,

(By the way I can't find what really differs from your fix to mine. Is it mandatory to pull git to update those settings ?)

**Comment by tporquet** [comment]
It shouldn't be mandatory to git pull to update. A local change in resources/predefined-settings.json
 should be taken in account after a simple page reload (or an ezpaarse restart). This is how I tested the change I made for you.
